// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejZu0XT0nrzQpiP-B-Sb4ZL7skK83U2U',
    appId: '1:681162785052:web:5914871cb10fcc82c07ad9',
    messagingSenderId: '681162785052',
    projectId: 'car-booking-32e91',
    authDomain: 'car-booking-32e91.firebaseapp.com',
    storageBucket: 'car-booking-32e91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYcJtsS2GkW489t8oe18y3k6KDe6k8w2g',
    appId: '1:681162785052:android:d46e0f4b26a65fb7c07ad9',
    messagingSenderId: '681162785052',
    projectId: 'car-booking-32e91',
    storageBucket: 'car-booking-32e91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYmA1oFSvLUlvCP7H8IX5m0AHIg_jc2Q',
    appId: '1:681162785052:ios:0f5affd3d3c98cb4c07ad9',
    messagingSenderId: '681162785052',
    projectId: 'car-booking-32e91',
    storageBucket: 'car-booking-32e91.firebasestorage.app',
    iosBundleId: 'com.example.carBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWYmA1oFSvLUlvCP7H8IX5m0AHIg_jc2Q',
    appId: '1:681162785052:ios:0f5affd3d3c98cb4c07ad9',
    messagingSenderId: '681162785052',
    projectId: 'car-booking-32e91',
    storageBucket: 'car-booking-32e91.firebasestorage.app',
    iosBundleId: 'com.example.carBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDejZu0XT0nrzQpiP-B-Sb4ZL7skK83U2U',
    appId: '1:681162785052:web:cff92720537fc501c07ad9',
    messagingSenderId: '681162785052',
    projectId: 'car-booking-32e91',
    authDomain: 'car-booking-32e91.firebaseapp.com',
    storageBucket: 'car-booking-32e91.firebasestorage.app',
  );
}
