// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFHJCvjuRUPPtOuft_5cZ0ioVyhvWAQc',
    appId: '1:1078282001843:web:04130b230e8b2a8bf6bfc6',
    messagingSenderId: '1078282001843',
    projectId: 'carbooking-ad9f2',
    authDomain: 'carbooking-ad9f2.firebaseapp.com',
    storageBucket: 'carbooking-ad9f2.firebasestorage.app',
    measurementId: 'G-DEYEQ91YVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qyF9my3zyCCVeCfOLAbuj-sbGJibtUg',
    appId: '1:1078282001843:android:101003b3acd12738f6bfc6',
    messagingSenderId: '1078282001843',
    projectId: 'carbooking-ad9f2',
    storageBucket: 'carbooking-ad9f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN3NaTnmzUei4B2ffcYeX3aB77nuE4i-I',
    appId: '1:1078282001843:ios:a0d8539dcdb775fef6bfc6',
    messagingSenderId: '1078282001843',
    projectId: 'carbooking-ad9f2',
    storageBucket: 'carbooking-ad9f2.firebasestorage.app',
    iosBundleId: 'com.example.carBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN3NaTnmzUei4B2ffcYeX3aB77nuE4i-I',
    appId: '1:1078282001843:ios:a0d8539dcdb775fef6bfc6',
    messagingSenderId: '1078282001843',
    projectId: 'carbooking-ad9f2',
    storageBucket: 'carbooking-ad9f2.firebasestorage.app',
    iosBundleId: 'com.example.carBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOFHJCvjuRUPPtOuft_5cZ0ioVyhvWAQc',
    appId: '1:1078282001843:web:3aae21879fb5694bf6bfc6',
    messagingSenderId: '1078282001843',
    projectId: 'carbooking-ad9f2',
    authDomain: 'carbooking-ad9f2.firebaseapp.com',
    storageBucket: 'carbooking-ad9f2.firebasestorage.app',
    measurementId: 'G-0EMBR22T52',
  );
}
